"use client";

import { useActionState } from "react";
import { Archive, Copy, Globe2, Plus, Trash2 } from "lucide-react";
import { FormFeedback } from "./FormFeedback";
import { applyHppPriceAction, archiveHppCostingAction, cloneHppCostingAction, createHppMasterAction, deleteHppMasterAction, saveHppMasterAction } from "@/lib/management/hpp-actions";
import { HPP_MASTER_CATEGORIES } from "@/lib/management/hpp";
import type { ManagementActionState } from "@/lib/management/validation";

const initial: ManagementActionState = { ok: false, message: "" };

export function HppRecordActions({ id }: { id: string }) {
  const [cloneState, cloneAction, cloning] = useActionState(cloneHppCostingAction, initial);
  const [archiveState, archiveAction, archiving] = useActionState(archiveHppCostingAction, initial);
  return <div className="hpp-record-actions"><FormFeedback state={cloneState} /><FormFeedback state={archiveState} /><form action={cloneAction}><input type="hidden" name="id" value={id} /><button disabled={cloning}><Copy />{cloning ? "Menyalin…" : "Duplikasi"}</button></form><form action={archiveAction}><input type="hidden" name="id" value={id} /><button className="danger" disabled={archiving}><Archive />{archiving ? "Mengarsipkan…" : "Arsipkan"}</button></form></div>;
}

export function ApplyHppPriceForm({ id, appliedPrice, departureId, departures }: { id: string; appliedPrice: number; departureId?: string | null; departures: Array<{ id: string; departureDate: string; price: string; package?: { name: string } }> }) {
  const [state, action, pending] = useActionState(applyHppPriceAction, initial);
  return <form action={action} className="management-form hpp-apply-form"><FormFeedback state={state} /><input type="hidden" name="id" value={id} /><div className="management-form-grid two"><label><span>Pilih paket keberangkatan *</span><select name="departureId" defaultValue={departureId ?? ""} required><option value="">-- Pilih paket yang ingin diperbarui --</option>{departures.map((item) => <option value={item.id} key={item.id}>{item.package?.name ?? "Paket"} — {item.departureDate} (Harga saat ini: Rp{Number(item.price).toLocaleString("id-ID")})</option>)}</select><small>Pilih jadwal paket mana yang harganya mau diubah.</small></label><label><span>Nominal harga baru *</span><input name="appliedPrice" inputMode="numeric" defaultValue={appliedPrice} required /><small>Periksa nominal di atas sebelum menerapkan ke website publik.</small></label></div><label className="hpp-apply-confirm"><input type="checkbox" name="confirmed" value="yes" required /><span>Saya yakin dan sudah memeriksa paket serta nominal harga baru di atas.</span></label><button className="admin-primary-button" disabled={pending}><Globe2 />{pending ? "Sedang memperbarui harga website…" : "Ya, Terapkan Harga ke Website"}</button></form>;
}

export function HppMasterPriceForm({ item }: { item: { id: string; name: string; amount: string; currency: string; costBasis: string; category: string; metadata: Record<string, unknown> } }) {
  const [state, action, pending] = useActionState(saveHppMasterAction, initial);
  const [deleteState, deleteAction, deleting] = useActionState(deleteHppMasterAction, initial);
  const hotel = item.category === "hotel_makkah" || item.category === "hotel_madinah";
  return <div className="hpp-master-row-wrap"><FormFeedback state={state} /><FormFeedback state={deleteState} /><form action={action} className={`hpp-master-row${hotel ? " hotel" : ""}`}><input type="hidden" name="id" value={item.id} /><span><strong>{item.name}</strong><small>Semua nilai berikut menjadi default simulasi baru.</small></span><label><small>Mata uang</small><select name="currency" defaultValue={item.currency} aria-label={`Mata uang ${item.name}`}><option>IDR</option><option>USD</option><option>SAR</option></select></label><label><small>Cara hitung</small><select name="costBasis" defaultValue={item.costBasis} aria-label={`Cara hitung ${item.name}`}><option value="per_pax">Per jamaah</option><option value="group">Total rombongan</option><option value="room_per_night">Per kamar / malam</option></select></label><label><small>Harga satuan</small><input name="amount" inputMode="decimal" defaultValue={Number(item.amount)} aria-label={`Harga ${item.name}`} /></label><label><small>Jumlah default</small><input name="defaultQuantity" inputMode="decimal" defaultValue={Number(item.metadata.defaultQuantity ?? 1)} aria-label={`Jumlah default ${item.name}`} /></label>{hotel ? <div className="hpp-master-seasons"><label><small>Low season</small><input name="low" inputMode="decimal" defaultValue={Number(item.metadata.low ?? item.amount)} /></label><label><small>Medium</small><input name="medium" inputMode="decimal" defaultValue={Number(item.metadata.medium ?? item.amount)} /></label><label><small>High season</small><input name="high" inputMode="decimal" defaultValue={Number(item.metadata.high ?? item.amount)} /></label></div> : null}<button disabled={pending}>{pending ? "Menyimpan…" : "Simpan perubahan"}</button></form><form action={deleteAction} className="hpp-master-delete"><input type="hidden" name="id" value={item.id} /><button type="submit" disabled={deleting} onClick={(event) => { if (!window.confirm(`Hapus “${item.name}” dari pilihan HPP? Simulasi lama tidak akan berubah.`)) event.preventDefault(); }} aria-label={`Hapus ${item.name}`}><Trash2 />{deleting ? "Menghapus…" : "Hapus"}</button></form></div>;
}

export function HppMasterCreateForm() {
  const [state, action, pending] = useActionState(createHppMasterAction, initial);
  return <form action={action} className="management-form hpp-master-create"><FormFeedback state={state} fieldLabels={{ name: "Nama biaya", category: "Kategori", currency: "Mata uang", costBasis: "Cara menghitung", amount: "Harga awal", defaultQuantity: "Jumlah default" }} /><div className="management-form-grid two"><label><span>Nama biaya atau hotel *</span><input name="name" placeholder="Contoh: Hotel Makkah Quad" required minLength={2} /><small>Gunakan nama yang mudah dikenali saat membuat perhitungan.</small></label><label><span>Kategori *</span><select name="category" defaultValue="other">{HPP_MASTER_CATEGORIES.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><small>Menentukan kelompok tempat master ini ditampilkan.</small></label><label><span>Mata uang *</span><select name="currency" defaultValue="IDR"><option>IDR</option><option>USD</option><option>SAR</option></select></label><label><span>Cara menghitung *</span><select name="costBasis" defaultValue="per_pax"><option value="per_pax">Per jamaah</option><option value="group">Total rombongan</option><option value="room_per_night">Per kamar / malam</option></select></label><label><span>Harga awal *</span><input name="amount" inputMode="decimal" defaultValue="0" required /><small>Boleh ditulis 16000000 atau 16.000.000.</small></label><label><span>Jumlah default *</span><input name="defaultQuantity" inputMode="decimal" defaultValue="1" required /><small>Contoh: 1 kali tiket atau 2 kali snack.</small></label></div><button className="admin-primary-button" disabled={pending}><Plus />{pending ? "Menambahkan…" : "Tambahkan ke master harga"}</button></form>;
}
