import Link from "next/link";
import { AlertTriangle, ArrowRight, Banknote, Boxes, CheckCircle2, Clock3, FileWarning, PackageCheck, UsersRound, WalletCards } from "lucide-react";

import type { getManagementContext } from "@/lib/management/data";
import { rupiah } from "@/lib/management/domain";
import { InitializeManagementButton, ManagementSettingsForm } from "./ManagementForms";
import { AdminPageHeader } from "./AdminUi";
import { CsvImportForm } from "./CsvImportForm";

type Context = Awaited<ReturnType<typeof getManagementContext>>;

function Empty({ children }: { children: React.ReactNode }) { return <div className="management-empty"><CheckCircle2 /><p>{children}</p></div>; }
function Status({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "good" | "warn" | "bad" | "neutral" }) { return <span className={`management-status ${tone}`}>{children}</span>; }
function DateText({ value }: { value: Date | string | null | undefined }) { return <>{value ? new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeZone: "Asia/Jakarta" }).format(new Date(value)) : "—"}</>; }

function Overview({ data }: { data: Context }) {
  const cards = [
    ["Jamaah aktif", data.dashboard.activePilgrims, UsersRound, "jamaah"],
    ["Pendaftaran", data.dashboard.registrations, PackageCheck, "keberangkatan"],
    ["Saldo kas & bank", rupiah(data.dashboard.netCash), Banknote, "keuangan"],
    ["Piutang jamaah", rupiah(data.dashboard.receivables), WalletCards, "pembayaran"],
  ] as const;
  return <>
    <AdminPageHeader eyebrow="MANAJEMEN INTERNAL" title="Ringkasan hari ini" description="Yang perlu diperhatikan tampil lebih dulu. Pilih satu pekerjaan untuk mulai." />
    {!data.settings ? <section className="management-setup"><div><strong>Siapkan data awal</strong><p>Buat kategori biaya dan daftar perlengkapan standar sekali saja.</p></div><InitializeManagementButton /></section> : null}
    <section className="management-kpis">{cards.map(([label, value, Icon, href]) => <Link key={label} href={`/admin/manajemen/${href}`}><span><Icon /></span><small>{label}</small><strong>{value}</strong><ArrowRight /></Link>)}</section>
    <div className="management-dashboard-columns">
      <section className="management-panel"><header><div><small>PERLU DITINDAK</small><h2>Pekerjaan penting</h2></div></header><div className="management-action-list">
        <Link href="/admin/manajemen/pembayaran"><Clock3 /><span><strong>{data.dashboard.dueSoon} pelunasan mendekati batas</strong><small>Periksa jamaah yang belum lunas menjelang H-30.</small></span><ArrowRight /></Link>
        <Link href="/admin/manajemen/dokumen"><FileWarning /><span><strong>{data.dashboard.incompleteDocuments} dokumen belum lengkap</strong><small>KTP, KK, atau dokumen pendukung masih perlu dilengkapi.</small></span><ArrowRight /></Link>
        <Link href="/admin/manajemen/stok"><Boxes /><span><strong>{data.dashboard.lowStock} barang menipis</strong><small>Stok sudah menyentuh batas minimum.</small></span><ArrowRight /></Link>
        <Link href="/admin/manajemen/agen-referral"><Banknote /><span><strong>{rupiah(data.dashboard.earnedCommission)} komisi siap dibayar</strong><small>Komisi jamaah lunas yang belum dibayarkan.</small></span><ArrowRight /></Link>
      </div></section>
      <section className="management-panel"><header><div><small>TERBARU</small><h2>Pendaftaran terakhir</h2></div><Link href="/admin/manajemen/keberangkatan">Lihat semua</Link></header>{data.bookings.length ? <div className="management-mini-list">{data.bookings.slice(0, 5).map((booking) => <div key={booking.id}><span><strong>{booking.payerName}</strong><small>{booking.bookingNumber} · {booking.registrations.length} jamaah</small></span><Status>{booking.status === "active" ? "Aktif" : booking.status}</Status></div>)}</div> : <Empty>Belum ada pendaftaran.</Empty>}</section>
    </div>
  </>;
}

function Pilgrims({ data }: { data: Context }) {
  return <><AdminPageHeader eyebrow="OPERASIONAL JAMAAH" title="Data Jamaah" description="Cari data jamaah dan tambahkan jamaah baru tanpa melewati form yang rumit." action={{ href: "/admin/manajemen/jamaah/baru", label: "Tambah jamaah" }} />
    <section className="management-panel"><header><div><small>{data.pilgrims.length} DATA</small><h2>Daftar jamaah</h2></div></header>{data.pilgrims.length ? <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Jamaah</th><th>Kontak</th><th>Dokumen</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{data.pilgrims.map((pilgrim) => { const docs = data.pilgrimDocuments.filter((doc) => doc.pilgrimId === pilgrim.id); return <tr key={pilgrim.id}><td><strong>{pilgrim.fullName}</strong><small>{pilgrim.passportNumber ? `Paspor ${pilgrim.passportNumber}` : "Paspor belum diisi"}</small></td><td>{pilgrim.whatsapp}<small>{pilgrim.email || "Email opsional"}</small></td><td>{docs.length} file</td><td><Status tone={pilgrim.status === "active" ? "good" : "neutral"}>{pilgrim.status === "active" ? "Aktif" : "Diarsipkan"}</Status></td><td><Link className="management-row-link" href={`/admin/manajemen/jamaah/${pilgrim.id}`}>Buka / Edit</Link></td></tr>; })}</tbody></table></div> : <Empty>Belum ada data jamaah.</Empty>}</section>
  </>;
}

function Departures({ data }: { data: Context }) {
  return <><AdminPageHeader eyebrow="OPERASIONAL PERJALANAN" title="Pendaftaran & keberangkatan" description="Pilih jamaah, paket, harga kesepakatan, dan agen dalam satu langkah." action={{ href: "/admin/manajemen/keberangkatan/baru", label: "Buat pendaftaran" }} />
    <section className="management-panel"><header><div><small>{data.bookings.length} BOOKING</small><h2>Pendaftaran jamaah</h2></div></header>{data.bookings.length ? <div className="management-card-list">{data.bookings.map((booking) => <Link className="management-record-card" href={`/admin/manajemen/keberangkatan/${booking.id}`} key={booking.id}><article><div><Status tone="good">{booking.bookingNumber}</Status><h3>{booking.payerName}</h3><p>{String(booking.packageSnapshot.name ?? "Paket")} · <DateText value={booking.departure?.departureDate} /></p></div><dl><div><dt>Jamaah</dt><dd>{booking.registrations.length}</dd></div><div><dt>Total tagihan</dt><dd>{rupiah(booking.registrations.reduce((sum, item) => sum + item.agreedPrice, 0))}</dd></div><div><dt>Agen</dt><dd>{booking.agent?.name ?? "—"}</dd></div></dl></article></Link>)}</div> : <Empty>Belum ada pendaftaran.</Empty>}</section>
  </>;
}

function Payments({ data }: { data: Context }) {
  return <><AdminPageHeader eyebrow="TRANSAKSI JAMAAH" title="Pembayaran jamaah" description="Catat uang masuk lalu bagikan ke jamaah. Status dan piutang dihitung otomatis." action={data.accounts.length ? { href: "/admin/manajemen/pembayaran/baru", label: "Catat pembayaran" } : undefined} />
    {!data.accounts.length ? <div className="management-warning"><AlertTriangle /><span>Tambahkan rekening atau kas di menu Kas & Keuangan sebelum mencatat pembayaran.</span></div> : null}
    <section className="management-panel"><header><div><small>{data.payments.length} TRANSAKSI</small><h2>Histori pembayaran</h2></div></header>{data.payments.length ? <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Tanggal</th><th>Booking</th><th>Metode</th><th>Nominal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{data.payments.map((item) => <tr key={item.id}><td><DateText value={item.paidAt} /></td><td><strong>{item.booking?.bookingNumber ?? "—"}</strong><small>{item.booking?.payerName}</small></td><td>{item.method}</td><td>{rupiah(item.amount)}</td><td><Status tone={item.status === "confirmed" ? "good" : "bad"}>{item.status === "confirmed" ? "Diterima" : "Dibatalkan"}</Status></td><td><Link className="management-row-link" href={`/admin/manajemen/pembayaran/${item.id}`}>Lihat detail</Link></td></tr>)}</tbody></table></div> : <Empty>Belum ada pembayaran.</Empty>}</section>
    <section className="management-panel"><header><div><small>STATUS OTOMATIS</small><h2>Tagihan per jamaah</h2></div></header>{data.registrations.length ? <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Jamaah</th><th>Paket</th><th>Terbayar</th><th>Sisa</th><th>Status</th><th>Jatuh tempo</th></tr></thead><tbody>{data.registrations.map((item) => <tr key={item.id}><td><strong>{item.pilgrim?.fullName ?? "—"}</strong><small>{item.booking?.bookingNumber}</small></td><td>{item.package?.name ?? "—"}</td><td>{rupiah(item.payment.netPaid)}</td><td>{rupiah(item.payment.outstanding)}</td><td><Status tone={item.payment.status === "Lunas" ? "good" : item.payment.partialRefund ? "bad" : "warn"}>{item.payment.partialRefund ? `${item.payment.status} · Refund sebagian` : item.payment.status}</Status></td><td><DateText value={item.dueAt} /></td></tr>)}</tbody></table></div> : <Empty>Belum ada tagihan jamaah.</Empty>}</section>
  </>;
}

function Finance({ data }: { data: Context }) {
  return <><AdminPageHeader eyebrow="KEUANGAN INTERNAL" title="Kas & keuangan" description="Saldo dipisah per rekening. Kas aktual dan piutang tidak dicampur." actions={[{ href: "/admin/manajemen/keuangan/baru?jenis=rekening", label: "Tambah rekening", secondary: data.accounts.length > 0 }, ...(data.accounts.length ? [{ href: "/admin/manajemen/keuangan/baru?jenis=transaksi", label: "Catat transaksi" }] : [])]} />
    <section className="management-account-grid">{data.accounts.map((account) => <Link className="management-record-card" href={`/admin/manajemen/keuangan/${account.id}`} key={account.id}><article><small>{account.type === "cash" ? "KAS TUNAI" : account.bankName || "REKENING"}</small><h3>{account.name}</h3><strong>{rupiah(account.balance)}</strong><p>{account.accountNumber || "Tanpa nomor rekening"}</p></article></Link>)}</section>
    <section className="management-panel"><header><div><small>TRANSAKSI TERBARU</small><h2>Arus kas</h2></div></header>{data.cashTransactions.length ? <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Tanggal</th><th>Keterangan</th><th>Jenis</th><th>Nominal</th><th>Aksi</th></tr></thead><tbody>{data.cashTransactions.slice(0, 50).map((item) => <tr key={item.id}><td><DateText value={item.transactionAt} /></td><td><strong>{item.description}</strong></td><td><Status tone={item.direction === "in" ? "good" : item.direction === "out" ? "bad" : "neutral"}>{item.direction === "in" ? "Masuk" : item.direction === "out" ? "Keluar" : "Transfer"}</Status></td><td>{rupiah(item.amount)}</td><td><Link className="management-row-link" href={`/admin/manajemen/keuangan/${item.id}`}>Lihat detail</Link></td></tr>)}</tbody></table></div> : <Empty>Belum ada transaksi kas.</Empty>}</section>
  </>;
}

function Agents({ data }: { data: Context }) { return <><AdminPageHeader eyebrow="PEMASARAN AGEN" title="Agen & referral" description="Setiap agen mendapat link unik. Komisi baru sah setelah jamaah lunas." action={{ href: "/admin/manajemen/agen-referral/baru", label: "Tambah agen" }} /><section className="management-panel"><header><div><small>{data.agents.length} AGEN</small><h2>Daftar agen</h2></div></header>{data.agents.length ? <div className="management-card-list compact">{data.agents.map((agent) => { const earned = data.commissions.filter((item) => item.agentId === agent.id && item.status === "earned").reduce((sum, item) => sum + item.amount, 0); return <Link className="management-record-card" href={`/admin/manajemen/agen-referral/${agent.id}`} key={agent.id}><article><div><Status tone={agent.status === "active" ? "good" : "neutral"}>{agent.status === "active" ? "Aktif" : "Arsip"}</Status><h3>{agent.name}</h3><p>{agent.whatsapp}</p><span>/ref/{agent.referralCode}</span></div><dl><div><dt>Komisi default</dt><dd>{rupiah(agent.defaultCommission)}</dd></div><div><dt>Siap dibayar</dt><dd>{rupiah(earned)}</dd></div></dl></article></Link>; })}</div> : <Empty>Belum ada agen.</Empty>}</section><section className="management-panel"><header><div><small>{data.leads.length} LEAD</small><h2>Calon jamaah dari link agen</h2></div></header>{data.leads.length ? <div className="management-mini-list">{data.leads.map((lead) => <div key={lead.id}><span><strong>{lead.name}</strong><small>{lead.agent?.name} · {lead.package?.name ?? "Belum pilih paket"} · {lead.whatsapp}</small></span><Status tone={lead.status === "converted" ? "good" : "warn"}>{lead.status === "new" ? "Baru" : lead.status}</Status></div>)}</div> : <Empty>Belum ada lead referral.</Empty>}</section></>; }

function Stock({ data }: { data: Context }) { return <><AdminPageHeader eyebrow="LOGISTIK UMRAH" title="Stok perlengkapan" description="Stok keluar tidak bisa melebihi barang yang tersedia." actions={[{ href: "/admin/manajemen/stok/baru?jenis=barang", label: "Tambah barang", secondary: data.inventory.length > 0 }, ...(data.inventory.length ? [{ href: "/admin/manajemen/stok/baru?jenis=pergerakan", label: "Catat stok" }] : [])]} /><section className="management-inventory-grid">{data.inventory.map((item) => <Link className="management-record-card" href={`/admin/manajemen/stok/${item.id}`} key={item.id}><article className={item.currentStock <= item.minimumStock ? "low" : ""}><span><Boxes /></span><div><small>{item.unit}</small><h3>{item.name}</h3><strong>{item.currentStock}</strong><p>Minimum {item.minimumStock}</p></div>{item.currentStock <= item.minimumStock ? <Status tone="warn">Menipis</Status> : <Status tone="good">Aman</Status>}</article></Link>)}</section></>; }

function Manifest({ data }: { data: Context }) { const genders = ["Laki-laki", "Perempuan"] as const; return <><AdminPageHeader eyebrow="KELOMPOK KEBERANGKATAN" title="Manifest & Room List" description="Susun kamar Quad, Triple, atau Double. Jamaah laki-laki dan perempuan selalu dipisahkan." action={data.registrations.length ? { href: "/admin/manajemen/manifest-room-list/baru", label: "Atur Room List" } : undefined} />{genders.map((gender) => { const rows = data.registrations.filter((item) => item.pilgrim?.gender === gender); return <section className="management-panel" key={gender}><header><div><small>ROOM LIST {gender.toUpperCase()}</small><h2>Jamaah {gender}</h2></div><Status>{rows.length} orang</Status></header>{rows.length ? <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Jamaah</th><th>Paket</th><th>Paspor</th><th>Tipe kamar</th><th>Nomor kamar</th><th>Aksi</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><strong>{item.pilgrim?.fullName}</strong></td><td>{item.package?.name}</td><td>{item.pilgrim?.passportNumber || "Belum diisi"}</td><td>{item.roomType ? item.roomType.charAt(0).toUpperCase() + item.roomType.slice(1) : "Belum diatur"}</td><td>{item.roomNumber || "—"}</td><td><Link className="management-row-link" href={`/admin/manajemen/manifest-room-list/${item.id}`}>Atur kamar</Link></td></tr>)}</tbody></table></div> : <Empty>Belum ada jamaah {gender.toLowerCase()}.</Empty>}</section>; })}{data.registrations.some((item) => !item.pilgrim?.gender) ? <div className="management-warning"><AlertTriangle /><span>{data.registrations.filter((item) => !item.pilgrim?.gender).length} jamaah belum memiliki jenis kelamin dan belum bisa dimasukkan ke Room List.</span></div> : null}</>; }

function Documents({ data }: { data: Context }) { return <><AdminPageHeader eyebrow="KELENGKAPAN DOKUMEN" title="Dokumen jamaah" description="Dokumen disimpan private dan hanya bisa dibuka melalui tautan sementara." action={{ href: "/admin/manajemen/dokumen/baru", label: "Upload dokumen" }} /><section className="management-panel"><header><div><small>CHECKLIST</small><h2>Kelengkapan jamaah</h2></div></header><div className="management-mini-list">{data.pilgrims.map((pilgrim) => { const docs = data.pilgrimDocuments.filter((item) => item.pilgrimId === pilgrim.id && item.reviewStatus !== "rejected"); const kinds = new Set(docs.map((item) => item.kind)); const complete = kinds.has("ktp") && kinds.has("kk") && (kinds.has("akta_lahir") || kinds.has("buku_nikah") || kinds.has("ijazah")); return <Link className="management-mini-link" href={`/admin/manajemen/dokumen/${pilgrim.id}`} key={pilgrim.id}><span><strong>{pilgrim.fullName}</strong><small>{docs.length} file tersimpan</small></span><Status tone={complete ? "good" : "warn"}>{complete ? "Lengkap" : "Belum lengkap"}</Status></Link>; })}</div></section></>; }

function Invoices({ data }: { data: Context }) { return <><AdminPageHeader eyebrow="DOKUMEN TRANSAKSI" title="Invoice & kwitansi" description="PDF proper, bernomor unik, tersimpan sebagai snapshot, dan dapat diunduh ulang." action={{ href: "/admin/manajemen/invoice-kwitansi/baru", label: "Terbitkan dokumen" }} /><section className="management-panel"><header><div><small>HISTORI PDF</small><h2>Dokumen diterbitkan</h2></div></header>{data.documents.length ? <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Nomor</th><th>Jenis</th><th>Tanggal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{data.documents.map((item) => <tr key={item.id}><td><strong>{item.number}</strong></td><td>{item.kind === "invoice" ? "Invoice" : "Kwitansi"}</td><td><DateText value={item.issuedAt} /></td><td><Status tone={item.status === "issued" ? "good" : "bad"}>{item.status === "issued" ? "Terbit" : "Dibatalkan"}</Status></td><td><Link className="management-row-link" href={`/admin/manajemen/invoice-kwitansi/${item.id}`}>Lihat detail</Link></td></tr>)}</tbody></table></div> : <Empty>Belum ada PDF diterbitkan.</Empty>}</section></>; }

function Reports({ data }: { data: Context }) { const realizedIncome = data.cashTransactions.filter((item) => item.direction === "in" && !item.isReversal).reduce((sum, item) => sum + item.amount, 0); const realizedExpense = data.cashTransactions.filter((item) => item.direction === "out" && !item.isReversal).reduce((sum, item) => sum + item.amount, 0); return <><AdminPageHeader eyebrow="REKAP BISNIS" title="Pusat laporan" description="Kas aktual, piutang, dan proyeksi ditampilkan terpisah agar mudah dipahami." /><section className="management-kpis reports"><article><small>Pemasukan aktual</small><strong>{rupiah(realizedIncome)}</strong></article><article><small>Pengeluaran aktual</small><strong>{rupiah(realizedExpense)}</strong></article><article><small>Selisih kas</small><strong>{rupiah(realizedIncome - realizedExpense)}</strong></article><article><small>Piutang</small><strong>{rupiah(data.dashboard.receivables)}</strong></article></section><section className="management-panel"><header><div><small>LABA REALISASI</small><h2>Laba per paket</h2></div></header><div className="management-table-wrap"><table className="management-table"><thead><tr><th>Paket</th><th>Pemasukan</th><th>Refund</th><th>Biaya</th><th>Komisi dibayar</th><th>Laba</th><th>Piutang</th></tr></thead><tbody>{data.packageFinancials.map((item) => <tr key={item.packageId}><td><strong>{item.packageName}</strong></td><td>{rupiah(item.income)}</td><td>{rupiah(item.refunded)}</td><td>{rupiah(item.expenses)}</td><td>{rupiah(item.commissions)}</td><td><strong>{rupiah(item.realizedProfit)}</strong></td><td>{rupiah(item.receivables)}</td></tr>)}</tbody></table></div></section><section className="management-panel"><header><div><small>DOWNLOAD</small><h2>Laporan siap diekspor</h2></div></header><div className="management-report-links">{[["jamaah", "Data jamaah"], ["manifest", "Manifest & Room List"], ["pembayaran", "Pembayaran & piutang"], ["kas", "Kas masuk & keluar"], ["laba", "Laba per paket"], ["komisi", "Komisi agen"], ["stok", "Stok perlengkapan"]].map(([type, label]) => <div key={type}><span><strong>{label}</strong><small>Excel untuk olah data · PDF untuk laporan formal</small></span><div><a href={`/api/admin/management/reports/${type}?format=xlsx`}>Excel</a><a href={`/api/admin/management/reports/${type}?format=pdf`}>PDF</a></div></div>)}</div></section></>; }

function Settings({ data }: { data: Context }) { return <><AdminPageHeader eyebrow="PENGATURAN" title="Pengaturan internal" description="Atur nilai default dan identitas yang dipakai pada transaksi serta PDF." /><section className="management-panel"><header><div><small>IDENTITAS & TRANSAKSI</small><h2>Pengaturan utama</h2></div></header><ManagementSettingsForm values={data.settings ? { companyName: data.settings.companyName, companyAddress: data.settings.companyAddress, companyPhone: data.settings.companyPhone, companyEmail: data.settings.companyEmail, defaultDpAmount: data.settings.defaultDpAmount, paymentDueDays: data.settings.paymentDueDays, financeSignerName: data.settings.financeSignerName, financeSignerTitle: data.settings.financeSignerTitle } : null} /></section><section className="management-panel"><header><div><small>IMPORT DATA LAMA</small><h2>Import CSV tervalidasi</h2></div></header><CsvImportForm /></section><section className="management-panel"><header><div><small>REKENING</small><h2>Rekening & kas aktif</h2></div></header><div className="management-mini-list">{data.accounts.map((account) => <div key={account.id}><span><strong>{account.name}</strong><small>{account.bankName || "Kas tunai"} · {account.accountNumber || "Tanpa nomor"}</small></span><Status tone={account.showOnInvoice ? "good" : "neutral"}>{account.showOnInvoice ? "Tampil di invoice" : "Internal"}</Status></div>)}</div></section></>; }

export function ManagementWorkspace({ module, data }: { module?: string; data: Context }) {
  if (!module) return <Overview data={data} />;
  if (module === "jamaah") return <Pilgrims data={data} />;
  if (module === "keberangkatan") return <Departures data={data} />;
  if (module === "pembayaran") return <Payments data={data} />;
  if (module === "keuangan") return <Finance data={data} />;
  if (module === "agen-referral") return <Agents data={data} />;
  if (module === "stok") return <Stock data={data} />;
  if (module === "manifest-room-list") return <Manifest data={data} />;
  if (module === "dokumen") return <Documents data={data} />;
  if (module === "invoice-kwitansi") return <Invoices data={data} />;
  if (module === "laporan") return <Reports data={data} />;
  if (module === "pengaturan") return <Settings data={data} />;
  return <Overview data={data} />;
}
